import React,{useEffect,useRef,useState} from 'react';
import * as Tooltip from '@radix-ui/react-tooltip';
import {levels,modules} from './curriculum.js';
import {createLab,run,goalMet} from './engine.js';
import {freshProgress,loadProgress,saveProgress,validateProgress,completeLevel,xpTotal,isUnlocked,moduleDone,streak} from './progress.js';
import {glossary,quizzes,cheats} from './reference.js';
import {Icon} from './icons.jsx';
import {IconButton,Modal,ProgressBar,download} from './ui.jsx';
import {Workspace} from './Lab.jsx';
import {ExpeditionShell,Atlas,Insignia} from './Expedition.jsx';
const padded=id=>String(id).padStart(3,'0');
const firstOpen=p=>levels.find(l=>!p.completed[l.id])?.id||128;
const session=l=>({lab:createLab(l),entries:[],history:[],done:0,assisted:false});
function initial(){let storage;try{storage=localStorage;}catch{}const progress=loadProgress(storage);try{if(!storage?.getItem('learn-k8s:progress:v1')&&window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)progress.settings.reduced=true;}catch{}const match=location.hash.match(/^#level=(\d+)$/),requested=Number(match?.[1]||progress.active),id=levels.some(l=>l.id===requested)&&isUnlocked(progress,requested)?requested:firstOpen(progress);return {progress,id};}
function tone(){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const ctx=new A();const gain=ctx.createGain();gain.gain.value=.035;gain.connect(ctx.destination);[523.25,659.25,783.99].forEach((f,i)=>{const o=ctx.createOscillator();o.frequency.value=f;o.connect(gain);o.start(ctx.currentTime+i*.09);o.stop(ctx.currentTime+.3+i*.09);});setTimeout(()=>ctx.close().catch(()=>{}),700);}catch{}}
export default function App(){
 const [view,setView]=useState(()=>/^#level=\d+$/.test(location.hash)?'lab':'atlas');
 const [boot]=useState(initial),[progress,setProgress]=useState(boot.progress),[id,setId]=useState(boot.id),[current,setCurrent]=useState(()=>session(levels[boot.id-1])),[command,setCommand]=useState(''),[sequence,setSequence]=useState(0),[modal,setModal]=useState(''),[courseModule,setCourseModule]=useState(null),[search,setSearch]=useState(''),[courseFilter,setCourseFilter]=useState('all'),[hint,setHint]=useState(0),[solution,setSolution]=useState(false),[reward,setReward]=useState(false),[rewardXp,setRewardXp]=useState(0),[toast,setToast]=useState(''),[resetDialog,setResetDialog]=useState(false),[storageFailed,setStorageFailed]=useState(false),[quizChoice,setQuizChoice]=useState(null),[glossarySearch,setGlossarySearch]=useState('');
 const inputRef=useRef(null),sessions=useRef({}),toastTimer=useRef(null),importRef=useRef(null);
 const level=levels[id-1],module=modules[level.module],completedCount=Object.keys(progress.completed).length,task=level.steps[current.done],isComplete=current.done===level.steps.length;
 function notify(text){setToast(text);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4500);}
 useEffect(()=>{try{setStorageFailed(!saveProgress(localStorage,progress));}catch{setStorageFailed(true);}},[progress]);
 useEffect(()=>()=>clearTimeout(toastTimer.current),[]);
 useEffect(()=>{const update=e=>{if(e.key==='learn-k8s:progress:v1'&&e.newValue){try{setProgress(validateProgress(JSON.parse(e.newValue)));notify('Diğer sekmedeki ilerleme kaydı alındı.');}catch{}}};window.addEventListener('storage',update);return()=>window.removeEventListener('storage',update);},[]);
 useEffect(()=>{document.documentElement.classList.toggle('reduce-motion',progress.settings.reduced);},[progress.settings.reduced]);
 useEffect(()=>{document.title=view==='atlas'?'Küme Seferleri — learn-k8s':`${padded(id)} · ${level.title} — learn-k8s`;},[id,view]);
 useEffect(()=>{const keyboard=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCourseModule(null);setModal('course');setTimeout(()=>document.querySelector('#course-search')?.focus(),80);}};window.addEventListener('keydown',keyboard);return()=>window.removeEventListener('keydown',keyboard);},[]);
 function go(next){if(!levels[next-1])return;if(!isUnlocked(progress,next)){notify('Önce önceki seviyeyi tamamla veya Ayarlar’dan serbest keşfi aç.');return;}setView('lab');if(next===id){setModal('');history.replaceState(null,'',`#level=${next}`);window.scrollTo({top:0,behavior:'instant'});return;}sessions.current[id]=current;setId(next);setCurrent(sessions.current[next]||session(levels[next-1]));setCommand('');setHint(0);setSolution(false);setReward(false);setModal('');setProgress(p=>({...p,active:next}));setSequence(x=>x+1);history.replaceState(null,'',`#level=${next}`);window.scrollTo({top:0,behavior:'instant'});}
 useEffect(()=>{const onHash=()=>{const m=location.hash.match(/^#level=(\d+)$/);if(m)go(Number(m[1]));else if(location.hash==='#map')setView('atlas');};window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash);},[id,progress,current]);
 function setting(key,value){setProgress(p=>({...p,settings:{...p.settings,[key]:value}}));}
 function execute(cmd){
  if(cmd==='clear'){setCurrent(c=>({...c,entries:[]}));return;}
  if(cmd==='history'){setCurrent(c=>({...c,entries:[...c.entries,{command:cmd,output:c.history.map((x,i)=>`${i+1}  ${x}`).join('\n')}].slice(-180)}));return;}
  const result=run(current.lab,cmd);let done=current.done;
  if(!result.error&&task&&goalMet(result.state,task.goal))done++;
  const next={...current,lab:result.state,entries:[...current.entries,{command:cmd,output:result.output,error:result.error}].slice(-180),history:[...current.history,cmd].slice(-150),done};
  setCurrent(next);setSequence(x=>x+1);
  if(done>current.done){setHint(0);setSolution(false);if(done===level.steps.length){setRewardXp(progress.completed[id]?0:level.xp);setProgress(p=>completeLevel(p,id,current.assisted));setReward(true);setQuizChoice(null);if(progress.settings.sound)tone();}else notify(`Adım ${done}/${level.steps.length} tamamlandı. Sonraki görev hazır.`);}
 }
 function restart(){setCurrent(session(level));setCommand('');setHint(0);setSolution(false);setResetDialog(false);setSequence(x=>x+1);notify('Laboratuvar başlangıç durumuna döndü. Kazandığın ilerleme korunuyor.');}
 function bookmark(){setProgress(p=>({...p,bookmarks:p.bookmarks.includes(id)?p.bookmarks.filter(x=>x!==id):[...p.bookmarks,id]}));}
 function openCourse(mod=null){setCourseModule(mod);setSearch('');setCourseFilter('all');setModal('course');}
 const courseLevels=levels.filter(l=>(courseModule===null||l.module===courseModule)&&(courseFilter==='all'||courseFilter==='done'&&progress.completed[l.id]||courseFilter==='bookmarked'&&progress.bookmarks.includes(l.id)||courseFilter==='open'&&isUnlocked(progress,l.id)&&!progress.completed[l.id])&&`${l.id} ${l.title} ${l.concept} ${modules[l.module].title}`.toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr')));
 async function importProgress(file){try{if(!file)return;if(file.size>1000000)throw new Error('İlerleme dosyası en fazla 1 MB olabilir.');const imported=validateProgress(JSON.parse(await file.text()));if(!window.confirm('Bu tarayıcıdaki ilerleme ve notlar, seçilen dosyayla değiştirilsin mi?'))return;setProgress(imported);sessions.current={};const next=isUnlocked(imported,imported.active)?imported.active:firstOpen(imported);setView('lab');setId(next);setCurrent(session(levels[next-1]));setCommand('');setReward(false);setModal('');setHint(0);setSolution(false);history.replaceState(null,'',`#level=${next}`);notify('İlerleme içe aktarıldı. Laboratuvar yeni oturumla açıldı.');}catch(e){notify(e.message);}finally{if(importRef.current)importRef.current.value='';}}
 function showMap(){setView('atlas');history.replaceState(null,'','#map');window.scrollTo({top:0,behavior:'instant'});}
 return <Tooltip.Provider><ExpeditionShell view={view} progress={progress} onMap={showMap} onLab={()=>go(id)} onCourse={openCourse} onModal={setModal}>
 {storageFailed&&<div className="storage-warning" role="alert">Tarayıcıya kayıt yapılamadı. Sekmeyi kapatmadan Ayarlar → İlerlemeyi dışa aktar kullan.</div>}
 {view==='atlas'&&<Atlas progress={progress} onGo={go} onCourse={openCourse} onModal={setModal}/>}
 <div className="lab-view" hidden={view!=='lab'}><div className="lab-breadcrumb"><button onClick={showMap}><Icon name="compass" size={15}/>Sefer haritası</button><Icon name="chevron" size={12}/><button onClick={()=>openCourse(level.module)}>{module.title}</button><span className="lab-view-mode">{progress.settings.free?'Serbest keşif':'Rehberli sefer'}</span><button className="reference-button" aria-label="Komut rehberi" onClick={()=>setModal('reference')}><Icon name="code" size={16}/><span>Komut rehberi</span></button></div>
 <div className="page-content"><section className="lesson-heading" id="lesson" tabIndex={-1}><div className="lesson-kicker"><span>MODÜL {String(level.module+1).padStart(2,'0')}</span><span>•</span><span>{level.difficulty}</span><span className="lesson-number">LAB {padded(id)} / 128</span></div><div className="lesson-title-row"><h1>{level.title}</h1><div className="lesson-actions"><IconButton icon="bookmark" label={progress.bookmarks.includes(id)?'Yer işaretini kaldır':'Seviyeyi işaretle'} aria-pressed={progress.bookmarks.includes(id)} onClick={bookmark}/><IconButton icon="reset" label="Laboratuvarı sıfırla" onClick={()=>setResetDialog(true)}/></div></div><div className="lesson-subline"><a className="jump-terminal" href="#terminal-input" onClick={e=>{e.preventDefault();inputRef.current?.focus();inputRef.current?.scrollIntoView({block:'center',behavior:'instant'});}}><Icon name="terminal" size={14}/>Terminale geç</a><span><Icon name="clock" size={14}/>{level.minutes} dk</span><span><Icon name="zap" size={14}/>{level.xp} XP</span><span>{level.steps.length} uygulama adımı</span>{progress.completed[id]&&<span className="completed-label"><Icon name="check" size={14}/>Tamamlandı · tekrar modu</span>}</div><div className="level-path" role="group" aria-label="Modüldeki seviyeler">{levels.filter(l=>l.module===level.module).map(l=><button key={l.id} className={`${l.id===id?'selected':''} ${progress.completed[l.id]?'done':''}`} disabled={!isUnlocked(progress,l.id)} onClick={()=>go(l.id)} aria-label={`Seviye ${l.id}: ${l.title}${progress.completed[l.id]?', tamamlandı':''}`} aria-current={l.id===id?'step':undefined}>{progress.completed[l.id]?<Icon name="check" size={13}/>:isUnlocked(progress,l.id)?String((l.id-1)%8+1).padStart(2,'0'):<Icon name="lock" size={12}/>}</button>)}<div className="path-end"><Icon name="trophy" size={18}/><span>{module.badge}</span></div></div></section>
 <div className="workbench"><section className="lesson-pane" aria-label="Ders anlatımı ve görevler"><div className="zone-marker zone-marker-briefing"><span>01 · BRIEFING</span><b>Oku · görevi anla</b></div><div className="field-note"><div className="note-heading"><span className="note-icon"><Icon name="book" size={17}/></span><span>SAHA NOTLARI</span><b>Önce anla.</b></div><h2>{level.module===0?'Paketi süreçten ayır.':'Neyi değiştireceğini bil.'}</h2><p>{level.concept}</p><div className="mechanism-bubble"><span><Icon name="link" size={14}/>Bu laboratuvarda</span><p>{level.mechanism}</p></div><details className="caution-note"><summary aria-label="Gerçek kümede aklında tut"><Icon name="info" size={15}/><span>Gerçek kümede</span><Icon name="chevron" size={13}/></summary><p>{level.caution}</p></details><a className="source-link" href={level.source} target="_blank" rel="noopener noreferrer">Resmî dokümanda devam et<Icon name="external" size={13}/></a></div>
 <section className={`mission ${isComplete?'mission-done':''}`}><div className="mission-heading"><span><Icon name="flag" size={17}/>Şimdi uygula.</span><b>{current.done}/{level.steps.length}</b></div><ProgressBar value={current.done} max={level.steps.length} label="Görev ilerlemesi"/><ol className="task-list">{level.steps.map((step,i)=><li key={i} className={i<current.done?'task-done':i===current.done?'task-current':'task-future'}><span className="task-index">{i<current.done?<Icon name="check" size={13}/>:i+1}</span><div><p>{step.text}</p>{i===current.done&&<span className="task-status">TERMİNALDE SIRA SENDE</span>}</div></li>)}</ol>{task?<div className="task-help"><button className="hint-button" onClick={()=>setHint(h=>Math.min(2,h+1))}><Icon name="hint" size={16}/>İpucu {hint?`${hint}/2`:''}</button><button className="solution-button" onClick={()=>{setSolution(v=>!v);setCurrent(c=>({...c,assisted:true}));}}>Çözümü {solution?'gizle':'gör'}</button>{hint>0&&<div className="hint-bubble"><b>{hint===1?'Bir yön işareti':'Sözdizimi desteği'}</b><p>{hint===1?task.hint:task.syntaxHint}</p></div>}{solution&&<div className="solution-box"><span>Komutu anlamını düşünerek çalıştır.</span><code>{task.command}</code><button onClick={()=>{setCommand(task.command);inputRef.current?.focus();}}>Terminale yerleştir<Icon name="arrow" size={13}/></button></div>}</div>:<div className="mission-success"><Icon name="check" size={20}/><p><b>İstenen durum doğrulandı.</b><span>Bu laboratuvarı tamamladın.</span></p><button className="button primary" onClick={()=>id<128?go(id+1):setModal('badges')}>{id<128?'Sonraki seviye':'Rozetlerini gör'}<Icon name="arrow" size={16}/></button></div>}</section>
 <details className="personal-notes"><summary><Icon name="file" size={16}/>Kendi notların <span>{progress.notes[id]?.length?'Kaydedildi':'Sadece bu tarayıcıda'}</span></summary><textarea aria-label="Bu seviye için notlarım" placeholder="Aklımda kalan ayrım, yeni bir soru…" maxLength={5000} value={progress.notes[id]||''} onChange={e=>setProgress(p=>({...p,notes:{...p.notes,[id]:e.target.value}}))}/></details><div className="lesson-pagination"><button disabled={id===1} onClick={()=>go(id-1)}><Icon name="arrow" size={15} style={{transform:'rotate(180deg)'}}/>Önceki</button><button onClick={()=>openCourse(level.module)}>8 seviyeye bak<Icon name="grid" size={14}/></button></div></section>
 <Workspace key={id} state={current.lab} level={level} sequence={sequence} entries={current.entries} onCommand={execute} command={command} setCommand={setCommand} inputRef={inputRef} history={current.history} onFiles={files=>setCurrent(c=>({...c,lab:{...c.lab,files}}))} notify={notify} settings={progress.settings} onSetting={setting}/></div></div></div></ExpeditionShell>
 <Modal open={modal==='course'} onOpenChange={v=>!v&&setModal('')} title="Öğrenme yolu" description="16 modül, 128 laboratuvar. Kavramı oku, dene ve sonucu doğrula." wide><div className="course-controls"><div className="search-field"><Icon name="search"/><input id="course-search" aria-label="Seviye ara" placeholder="Pod, Secret, autoscaling…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filter-row"><select aria-label="Modül filtresi" value={courseModule??'all'} onChange={e=>setCourseModule(e.target.value==='all'?null:Number(e.target.value))}><option value="all">Bütün modüller</option>{modules.map(m=><option key={m.id} value={m.id}>{m.id+1}. {m.title}</option>)}</select><select aria-label="İlerleme filtresi" value={courseFilter} onChange={e=>setCourseFilter(e.target.value)}><option value="all">Bütün seviyeler</option><option value="open">Sıradaki açık seviyeler</option><option value="done">Tamamlananlar</option><option value="bookmarked">Yer işaretleri</option></select><span>{courseLevels.length} seviye</span></div></div><div className="course-list" tabIndex={0} role="region" aria-label="Filtrelenen seviyeler">{courseLevels.length?courseLevels.map(l=><button key={l.id} className={`course-row ${l.id===id?'current':''}`} disabled={!isUnlocked(progress,l.id)} onClick={()=>go(l.id)}><span className="course-id">{padded(l.id)}</span><div><small>{modules[l.module].title}</small><strong>{l.title}</strong><p>{l.steps.length} görev · {l.minutes} dk · {l.xp} XP</p></div><Icon name={progress.completed[l.id]?'check':isUnlocked(progress,l.id)?'arrow':'lock'} size={17}/></button>):<p className="empty-message">Bu filtreye uyan seviye yok.</p>}</div><p className="dialog-footnote">Sırayla ilerlemek temelleri pekiştirir. Belirli bir konuyu incelemek için Ayarlar’dan serbest keşfi açabilirsin.</p></Modal>
 <Modal open={modal==='glossary'} onOpenChange={v=>!v&&setModal('')} title="Kavram sözlüğü" description={`${glossary.length} kavram. Ezberlenecek tanımlar değil, karıştırılmaması gereken ayrımlar.`} wide><div className="search-field glossary-search"><Icon name="search"/><input aria-label="Sözlükte ara" placeholder="Örn. readiness veya PVC" value={glossarySearch} onChange={e=>setGlossarySearch(e.target.value)}/></div><div className="glossary-grid">{glossary.filter(g=>`${g.term} ${g.definition}`.toLocaleLowerCase('tr').includes(glossarySearch.toLocaleLowerCase('tr'))).map(g=><article key={g.term}><span>{g.category}</span><h3>{g.term}</h3><p>{g.definition}</p></article>)}</div></Modal>
 <Modal open={modal==='reference'} onOpenChange={v=>!v&&setModal('')} title="Terminal cep rehberi" description="NAME, IMAGE ve FILE yer tutucularını görevdeki değerlerle değiştir. lab komutları Kubernetes komutu değildir." wide><div className="cheat-grid">{cheats.map(([title,commands])=><section key={title}><h3>{title}</h3><pre>{commands}</pre></section>)}</div><p className="dialog-footnote">Tırnaklar ve seçenek sırası desteklenir; pipe, shell, gerçek ağ ve dosya sistemi desteklenmez. Tam yerel liste için terminalde help yaz.</p></Modal>
 <Modal open={modal==='badges'} onOpenChange={v=>!v&&setModal('')} title="Sefer rozetleri" description={`${completedCount} seviye tamamlandı · ${xpTotal(progress).toLocaleString('tr')} XP · ${streak(progress)} günlük öğrenme serisi`} wide><div className="badge-grid">{modules.map(m=><div key={m.id} className={`badge-card ${moduleDone(progress,m.id)?'earned':''}`}><span className="badge-seal"><Insignia module={m.id} size={60}/></span><span className="eyebrow">MODÜL {m.id+1}</span><h3>{m.badge}</h3><p>{levels.filter(l=>l.module===m.id&&progress.completed[l.id]).length}/8 seviye</p>{progress.quiz[m.id]&&<small>✓ Kavram kontrolü</small>}</div>)}</div><p className="dialog-footnote">Rozetler bu aracın öğrenme ilerlemesidir; bir sertifika veya gerçek küme yeterlilik belgesi değildir.</p></Modal>
 <Modal open={modal==='settings'} onOpenChange={v=>!v&&setModal('')} title="Seyir ayarları" description="Öğrenme yolu sana uysun. İlerleme bu cihazın tarayıcısında saklanır."><div className="settings-body">{[['free','Serbest keşif','Ön koşulları beklemeden bütün seviyeleri aç. XP yalnız görev tamamlandığında kazanılır.'],['reduced','Hareketi azalt','Olayları anında göster; animasyonları azalt. Sistem tercihi de dikkate alınır.'],['sound','Tamamlama sesi','Bir seviye tamamlandığında kısa bir ses çal. Varsayılan kapalıdır.']].map(([key,title,desc])=><label className="setting-row" key={key}><span><b>{title}</b><small>{desc}</small></span><input type="checkbox" checked={progress.settings[key]} onChange={e=>setting(key,e.target.checked)}/></label>)}<div className="data-section"><h3>İlerleme seninle gelsin.</h3><p>Başka cihaza geçmeden JSON yedeği indir. Dosya notlarını, rozetlerini ve ayarlarını içerir; terminal oturumunu içermez.</p><div className="button-row"><button className="button secondary" onClick={()=>download('learn-k8s-progress.json',JSON.stringify(progress,null,2))}><Icon name="download"/>Dışa aktar</button><button className="button secondary" onClick={()=>importRef.current?.click()}><Icon name="upload"/>İçe aktar</button></div><input ref={importRef} type="file" accept="application/json,.json" hidden onChange={e=>importProgress(e.target.files?.[0])}/></div><button className="danger-link" onClick={()=>{if(window.confirm('Bütün ilerleme, not ve rozetler bu tarayıcıdan silinsin mi? Bu işlem geri alınamaz.')){const p=freshProgress();setProgress(p);sessions.current={};setView('lab');setId(1);setCurrent(session(levels[0]));setCommand('');setModal('');setReward(false);setHint(0);setSolution(false);history.replaceState(null,'','#level=1');notify('Yerel öğrenme kaydı sıfırlandı.');}}}>Bütün yerel ilerlemeyi sil</button></div></Modal>
 <Modal open={modal==='about'} onOpenChange={v=>!v&&setModal('')} title="Bu bir öğrenme modeli." description="Gerçek Kubernetes çalıştırmadan doğru zihinsel modeli kurmaya odaklanır."><div className="about-body"><h3>Durum gerçekten değişir; altyapı çalışmaz.</h3><p>Komutlar bellek içindeki kaynak nesnelerini değiştirir. Controller, scheduler, Service hedefleri, sınırlı RBAC ve ağ politikası kuralları sonucu hesaplar. Görevler bu sonuçlara bakar.</p><h3>Neleri sadeleştiriyoruz?</h3><p>Rollout anlık ve kapasite bakımından basitleştirilmiştir; maxSurge, backoff, probe süreleri, CPU throttling, gerçek disk verisi, CNI, TLS, sertifika ve Helm template motoru çalışmaz. lab tick gerçek zaman değildir.</p><h3>Güvenlik ve gizlilik</h3><p>Hesap, analiz takibi veya sunucu isteği yoktur. İlerleme localStorage’da tutulur. Gerçek Secret, parola, kubeconfig veya şirket manifestlerini buraya yapıştırma. Dış doküman bağlantıları ayrı sekmede açılır.</p><h3>Gerçek kümeye geçiş</h3><p>Burada öğrendiğin komutların gerçek ortamda kaynak oluşturabileceğini veya silebileceğini unutma. Ayrı bir kind/minikube çalışma kümesi, doğru context ve resmî dokümanlarla devam et.</p><a className="source-link" href="https://kubernetes.io/docs/tutorials/kubernetes-basics/" target="_blank" rel="noopener noreferrer">Kubernetes Basics<Icon name="external" size={14}/></a></div></Modal>
 <Modal open={resetDialog} onOpenChange={setResetDialog} title="Bu laboratuvar yeniden başlasın mı?" description="Kaynaklar, terminal geçmişi ve bu oturumdaki YAML değişiklikleri başlangıca döner. Kazanılmış XP, notlar ve rozetler silinmez."><div className="confirm-actions"><button className="button secondary" onClick={()=>setResetDialog(false)}>Vazgeç</button><button className="button primary" onClick={restart}><Icon name="reset"/>Laboratuvarı sıfırla</button></div></Modal>
 <Modal open={reward} onOpenChange={setReward} title={id===128?'Küme kaptanı, sefer tamamlandı.':id%8===0&&moduleDone(progress,level.module)?`${module.badge} rozeti senin.`:'Bir durak daha geride.'} description={id%8===0&&moduleDone(progress,level.module)?'Bu modülün sekiz laboratuvarını da tamamladın.':'Komutu çalıştırdın. İstenen sonucu doğruladın.'}><div className="reward-body"><div className="reward-seal"><Insignia module={level.module} size={76}/></div><div className="reward-meta"><span>LAB {padded(id)} TAMAMLANDI</span><strong>{rewardXp?`+${rewardXp} XP`:'Tekrar tamamlandı'}</strong></div><p>{level.title}</p>{current.assisted&&<span className="guided-completion">Rehber desteğiyle öğrenmek de ilerlemektir.</span>}{id%8===0&&<div className="quiz-box"><span className="eyebrow">KAVRAM KONTROLÜ · İSTEĞE BAĞLI</span><h3>{quizzes[level.module].question}</h3>{quizzes[level.module].options.map((option,i)=><button key={i} className={quizChoice===i?(i===quizzes[level.module].answer?'correct':'incorrect'):''} onClick={()=>{setQuizChoice(i);if(i===quizzes[level.module].answer)setProgress(p=>({...p,quiz:{...p.quiz,[level.module]:true}}));}}>{option}</button>)}{quizChoice!==null&&<p role="status">{quizChoice===quizzes[level.module].answer?'Doğru. ': 'Bir daha düşün. '}{quizzes[level.module].explanation}</p>}</div>}<button className="button primary reward-next" onClick={()=>{setReward(false);if(id<128)go(id+1);else setModal('badges');}}>{id===128?'Yolculuğunu gör':'Sonraki laboratuvara geç'}<Icon name="arrow"/></button><button className="text-button" onClick={()=>setReward(false)}>Burada denemeye devam et</button></div></Modal>
 {toast&&<div className="toast" role="status"><Icon name="info" size={17}/>{toast}<button aria-label="Bildirimi kapat" onClick={()=>setToast('')}><Icon name="close" size={14}/></button></div>}
 </Tooltip.Provider>;
}
