import {t,formatNumber,searchText,getLanguage} from './i18n.js';
import {useLanguage} from './Language.jsx';
import {localizedCurriculum,localizedReference} from './localize.js';
import {runtimeText} from './runtime-text.js';
import React,{useEffect,useRef,useState} from 'react';
import * as Tooltip from '@radix-ui/react-tooltip';
import {levels} from './curriculum.js';
import {run} from './engine.js';
import {advanceSession, evaluateTask, createChallenge, challengeKinds, predictionFor} from './learning.js';
import {freshSession,loadSession,restoreSession,saveSession,clearSession,snapshotBeforeCommand} from './session.js';
import {ReferenceSolution, PracticeCenter, Prediction} from './PracticeTools.jsx';
import {freshProgress,loadProgress,saveProgress,validateProgress,completeLevel,xpTotal,isUnlocked,moduleDone,streak,lessonKey,lessonId,PROGRESS_KEY,LEGACY_PROGRESS_KEY,needsReview,today} from './progress.js';
import {Icon} from './icons.jsx';
import {IconButton,Modal,ProgressBar,download} from './ui.jsx';
import {Workspace} from './Lab.jsx';
import {LessonTabs} from './LessonTabs.jsx';
import {ExpeditionShell,Atlas,Insignia} from './Expedition.jsx';
import {PixelConfetti,useCompletionReward} from './RewardCelebration.jsx';
const padded=id=>String(id).padStart(3,'0');
const firstOpen=p=>levels.find(l=>!p.completed[l.key])?.id||128;
const session = freshSession;
function routeFromHash() {
 const params=new URLSearchParams(location.hash.slice(1));
 const raw=params.get('level'), id=raw&&/^\d+$/.test(raw)?Number(raw):null;
 const kind=params.get('challenge'), rawSeed=params.get('seed')??'1';
 return {id,variant:kind?{kind,seed:/^\d+$/.test(rawSeed)?Number(rawSeed):-1}:null};
}
function challengeFor(variant,id,locale=getLanguage()) {
 if(!variant||!Number.isInteger(variant.seed)||variant.seed<0||variant.seed>2147483647)return null;
 try { const level=createChallenge(variant.kind,variant.seed,locale); return level.sourceId===id?level:null; } catch { return null; }
}
const levelHash=level=>`#level=${level.sourceId||level.id}${level.challenge?`&challenge=${level.challengeKind}&seed=${level.challengeSeed}`:''}`;
function initial() {
 let storage; try { storage = localStorage; } catch {}
 const progress = loadProgress(storage);
 try { if (!storage?.getItem(PROGRESS_KEY) && !storage?.getItem(LEGACY_PROGRESS_KEY) && window.matchMedia?.('(prefers-reduced-motion: reduce)').matches) progress.settings.reduced = true; } catch {}
 const route=routeFromHash();
 const requested=route.id||lessonId(progress.active);
 const id=levels.some(level=>level.id===requested)&&isUnlocked(progress,requested)?requested:firstOpen(progress);
 const saved=loadSession(storage);
 const variant=route.variant||(!route.id&&saved?.lessonKey===levels[id-1].key?saved.session.variant:null);
 const level=challengeFor(variant,id)||levels[id-1];
 const current=restoreSession(saved,level)||session(level);
 return {progress:{...progress,active:level.sourceKey||level.key}, id, current, invalidVariant:!!variant&&!level.challenge};
}
function tone(){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const ctx=new A();const gain=ctx.createGain();gain.gain.value=.035;gain.connect(ctx.destination);[523.25,659.25,783.99].forEach((f,i)=>{const o=ctx.createOscillator();o.frequency.value=f;o.connect(gain);o.start(ctx.currentTime+i*.09);o.stop(ctx.currentTime+.3+i*.09);});setTimeout(()=>ctx.close().catch(()=>{}),700);}catch{}}
export default function App(){
 const language=useLanguage();
 const {levels,modules}=localizedCurriculum(language);
 const {glossary,quizzes,cheats}=localizedReference(language);
 const [view,setView]=useState(()=>routeFromHash().id?'lab':'atlas');
 const [boot]=useState(initial),[progress,setProgress]=useState(boot.progress),[id,setId]=useState(boot.id),[current,setCurrent]=useState(boot.current),[command,setCommand]=useState(boot.current.commandDraft),[sequence,setSequence]=useState(0),[modal,setModal]=useState(''),[courseModule,setCourseModule]=useState(null),[search,setSearch]=useState(''),[courseFilter,setCourseFilter]=useState('all'),[hint,setHint]=useState(0),[solution,setSolution]=useState(false),[rewardXp,setRewardXp]=useState(0),[toast,setToast]=useState(''),[resetDialog,setResetDialog]=useState(false),[storageFailed,setStorageFailed]=useState(false),[sessionFailed,setSessionFailed]=useState(false),[quizChoice,setQuizChoice]=useState(null),[glossarySearch,setGlossarySearch]=useState(''),[headerCollapsed,setHeaderCollapsed]=useState(false);
 const inputRef=useRef(null),sessions=useRef({}),toastTimer=useRef(null),importRef=useRef(null);
 const level=challengeFor(current.variant,id,language)||levels[id-1],progressKey=level.sourceKey||level.key,module=modules[level.module],completedCount=Object.keys(progress.completed).length,task=level.steps[current.done],isComplete=current.done===level.steps.length;
 const {open:reward,queue:queueReward,dismiss:closeReward,reducedMotion:rewardReduced}=useCompletionReward({levelId:level.key,visible:view==='lab',blocked:Boolean(modal)||resetDialog,reduced:progress.settings.reduced});
 function notify(text){setToast(text);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4500);}
 useEffect(()=>{if(boot.invalidVariant){history.replaceState(null,'',`#level=${id}`);notify(t('Bu senaryo bağlantısı geçersiz. Rehberli lab açıldı.'));}},[]);
 useEffect(()=>{try{setStorageFailed(!saveProgress(localStorage,progress));}catch{setStorageFailed(true);}},[progress]);
 useEffect(()=>()=>clearTimeout(toastTimer.current),[]);
 useEffect(()=>{
  const persist=()=>{try{setSessionFailed(!saveSession(localStorage,level,current,command));}catch{setSessionFailed(true);}};
  const timer=setTimeout(persist,180);
  window.addEventListener('pagehide',persist);
  return()=>{clearTimeout(timer);window.removeEventListener('pagehide',persist);};
 },[current,command,level.key]);
 useEffect(()=>{const update=e=>{if(e.key===PROGRESS_KEY&&e.newValue){try{setProgress(validateProgress(JSON.parse(e.newValue)));notify(t('Diğer sekmedeki ilerleme kaydı alındı.'));}catch{}}};window.addEventListener('storage',update);return()=>window.removeEventListener('storage',update);},[]);
 useEffect(()=>{document.documentElement.classList.toggle('reduce-motion',progress.settings.reduced);},[progress.settings.reduced]);
 useEffect(()=>{document.title=view==='atlas'?t('Küme Seferleri — learn-k8s'):`${padded(id)} · ${level.title} — learn-k8s`;},[id,level.key,view,language]);
 useEffect(()=>{const keyboard=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCourseModule(null);setModal('course');setTimeout(()=>document.querySelector('#course-search')?.focus(),80);}};window.addEventListener('keydown',keyboard);return()=>window.removeEventListener('keydown',keyboard);},[]);
 function enterLevel(nextLevel,{fresh=false}={}) {
  const next=nextLevel.sourceId||nextLevel.id;
  if(!isUnlocked(progress,next)){notify(t('Önce önceki seviyeyi tamamla veya Ayarlar’dan serbest keşfi aç.'));return;}
  closeReward();setView('lab');setModal('');
  if(nextLevel.key!==level.key||fresh){
   sessions.current[level.key]={...current,commandDraft:command};
   const resumed=(!fresh&&sessions.current[nextLevel.key])||session(nextLevel);
   setId(next);setCurrent(resumed);setCommand(resumed.commandDraft||'');
   setHint(0);setSolution(false);setSequence(value=>value+1);
  }
  setProgress(value=>({...value,active:nextLevel.sourceKey||nextLevel.key}));
  history.replaceState(null,'',levelHash(nextLevel));window.scrollTo({top:0,behavior:'instant'});
 }
 function go(next,options) {if(levels[next-1])enterLevel(levels[next-1],options);}
 function resumeActive(){enterLevel(level);}
 function startChallenge(kind,seed){const next=challengeFor({kind,seed},lessonId(challengeKinds.find(item=>item.kind===kind)?.sourceKey),language);if(next)enterLevel(next,{fresh:true});}
 function allReviews(){setCourseModule(null);setSearch('');setCourseFilter('review');setModal('course');}
 useEffect(()=>{
  const onHash=()=>{
   const route=routeFromHash();
   if(route.id){const challenge=challengeFor(route.variant,route.id,language);if(challenge)enterLevel(challenge);else{go(route.id);if(route.variant)notify(t('Bu senaryo bağlantısı geçersiz. Rehberli lab açıldı.'));}}
   else if(location.hash==='#map')showMap();
  };
  window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash);
 },[id,progress,current,command,language]);
 function setting(key,value){setProgress(p=>({...p,settings:{...p.settings,[key]:value}}));}
 function execute(cmd){
  if(cmd==='clear'){setCurrent(c=>({...c,entries:[],previousState:snapshotBeforeCommand(c.lab)}));return;}
  if(cmd==='history'){setCurrent(c=>({...c,previousState:snapshotBeforeCommand(c.lab),entries:[...c.entries,{command:cmd,output:c.history.map((x,i)=>`${i+1}  ${x}`).join('\n')}].slice(-180)}));return;}
  const result=run(current.lab,cmd);
  const assessment=advanceSession(level,current,result);
  const next={...current,...assessment,lab:result.state,previousState:snapshotBeforeCommand(current.lab),entries:[...current.entries,{command:cmd,output:result.output,error:result.error,event:result.event}].slice(-180),history:[...current.history,cmd].slice(-150)};
  setCurrent(next);setSequence(value=>value+1);
  if(assessment.done>current.done){
   setHint(0);setSolution(false);
   if(assessment.justCompleted){
    clearTimeout(toastTimer.current);setToast('');setRewardXp(progress.completed[progressKey]?0:level.xp);
    setProgress(value=>completeLevel(value,progressKey,current.assisted,today(),{challenge:!!level.challenge}));queueReward();setQuizChoice(null);
    if(progress.settings.sound)tone();
   }else notify(t('Adım {0}/{1} tamamlandı. Sonraki görev hazır.',[assessment.done,level.steps.length]));
  }
 }
 function restart(){closeReward();setCurrent(session(level));setCommand('');setHint(0);setSolution(false);setResetDialog(false);setSequence(x=>x+1);notify(t('Laboratuvar başlangıç durumuna döndü. Kazandığın ilerleme korunuyor.'));}
 function bookmark(){setProgress(p=>({...p,bookmarks:p.bookmarks.includes(progressKey)?p.bookmarks.filter(x=>x!==progressKey):[...p.bookmarks,progressKey]}));}
 function openCourse(mod=null){setCourseModule(mod);setSearch('');setCourseFilter('all');setModal('course');}
 const courseLevels=levels.filter(l=>(courseModule===null||l.module===courseModule)&&(courseFilter==='all'||courseFilter==='done'&&progress.completed[l.key]||courseFilter==='bookmarked'&&progress.bookmarks.includes(l.key)||courseFilter==='open'&&isUnlocked(progress,l.id)&&!progress.completed[l.key]||courseFilter==='review'&&needsReview(progress,l.key)||courseFilter==='assisted'&&progress.completed[l.key]&&!progress.practice[l.key]?.lastIndependentSuccess)&&searchText(`${l.id} ${l.title} ${l.concept} ${modules[l.module].title}`).includes(searchText(search)));
 async function importProgress(file){try{if(!file)return;if(file.size>1000000)throw new Error(t('İlerleme dosyası en fazla 1 MB olabilir.'));const imported=validateProgress(JSON.parse(await file.text()));if(!window.confirm(t('Bu tarayıcıdaki ilerleme ve notlar, seçilen dosyayla değiştirilsin mi?')))return;setProgress(imported);try{clearSession(localStorage);}catch{}sessions.current={};const next=isUnlocked(imported,imported.active)?lessonId(imported.active):firstOpen(imported);setView('lab');setId(next);setCurrent(session(levels[next-1]));setCommand('');closeReward();setModal('');setHint(0);setSolution(false);history.replaceState(null,'',`#level=${next}`);notify(t('İlerleme içe aktarıldı. Laboratuvar yeni oturumla açıldı.'));}catch(e){notify(runtimeText(e.message));}finally{if(importRef.current)importRef.current.value='';}}
 function showMap(){closeReward();setView('atlas');history.replaceState(null,'','#map');window.scrollTo({top:0,behavior:'instant'});}
 return <Tooltip.Provider><ExpeditionShell view={view} progress={progress} onMap={showMap} onLab={resumeActive} onCourse={openCourse} onModal={setModal}>
 {(storageFailed||sessionFailed)&&<div className="storage-warning" role="alert">{storageFailed?t('Tarayıcıya kayıt yapılamadı. Sekmeyi kapatmadan Ayarlar → İlerlemeyi dışa aktar kullan.'):t('Bu laboratuvarın oturumu kaydedilemedi. Sekmeyi kapatmadan YAML taslaklarını kopyala.')}</div>}
 {view==='atlas'&&<Atlas progress={progress} onGo={go} onResume={next=>next===id?resumeActive():go(next)} onCourse={openCourse} onModal={setModal}/>}
 <div className={`lab-view ${headerCollapsed?'header-collapsed':''}`} hidden={view!=='lab'}><div className="lab-breadcrumb"><button onClick={showMap}><Icon name="compass" size={15}/>{t('Sefer haritası')}</button><Icon name="chevron" size={12}/><button onClick={()=>openCourse(level.module)}>{module.title}</button><span className="lab-view-mode">{progress.settings.free?t('Serbest keşif'):t('Rehberli sefer')}</span><button className="reference-button" aria-label={t('Komut rehberi')} onClick={()=>setModal('reference')}><Icon name="code" size={16}/><span>{t('Komut rehberi')}</span></button><button className="practice-launch" onClick={()=>setModal('practice')}><Icon name="flag" size={15}/>{t('Alıştırmalar')}</button></div>
 <div className="page-content">{level.challenge&&<div className="challenge-banner"><strong>{t('Bağımsız senaryo')} · #{level.challengeSeed}</strong><button onClick={()=>go(id)}>{t('Rehberli lab’a dön')}</button><button onClick={()=>startChallenge(level.challengeKind,(level.challengeSeed+1)%2147483648)}>{t('Yeni varyant')}</button></div>}<section className={`lesson-heading ${headerCollapsed?'is-collapsed':''}`} id="lesson" tabIndex={-1}><div className="lesson-kicker"><span>{t('MODÜL')} {String(level.module+1).padStart(2,'0')}</span><span>•</span><span>{level.difficulty}</span><span className="lesson-number">LAB {padded(id)} / 128</span></div><div className="lesson-title-row"><h1>{level.title}</h1><div className="lesson-actions"><span className="lesson-collapse-control"><IconButton icon="chevron" label={headerCollapsed?t('Üst bölümü genişlet'):t('Üst bölümü daralt')} aria-expanded={!headerCollapsed} aria-controls="lesson-header-details" onClick={()=>setHeaderCollapsed(v=>!v)}/></span><IconButton icon="bookmark" label={progress.bookmarks.includes(progressKey)?t('Yer işaretini kaldır'):t('Seviyeyi işaretle')} aria-pressed={progress.bookmarks.includes(progressKey)} onClick={bookmark}/><IconButton icon="reset" label={t('Laboratuvarı sıfırla')} onClick={()=>setResetDialog(true)}/></div></div><div id="lesson-header-details" className="lesson-header-details"><div className="lesson-subline"><a className="jump-terminal" href="#terminal-input" onClick={e=>{e.preventDefault();inputRef.current?.focus();inputRef.current?.scrollIntoView({block:'center',behavior:'instant'});}}><Icon name="terminal" size={14}/>{t('Terminale geç')}</a><span><Icon name="clock" size={14}/>{level.minutes} {t('dk')}</span><span><Icon name="zap" size={14}/>{level.xp} XP</span><span>{t('{0} uygulama adımı',[level.steps.length])}</span>{progress.completed[progressKey]&&<span className="completed-label"><Icon name="check" size={14}/>{t('Tamamlandı · tekrar modu')}</span>}</div><div className="level-path" role="group" aria-label={t('Modüldeki seviyeler')}>{levels.filter(l=>l.module===level.module).map(l=><button key={l.id} className={`${l.id===id?'selected':''} ${progress.completed[l.key]?'done':''}`} disabled={!isUnlocked(progress,l.id)} onClick={()=>go(l.id)} aria-label={t('Seviye {0}: {1}{2}',[l.id,l.title,progress.completed[l.key]?t(', tamamlandı'):''])} aria-current={l.id===id?'step':undefined}>{progress.completed[l.key]?<Icon name="check" size={13}/>:isUnlocked(progress,l.id)?String((l.id-1)%8+1).padStart(2,'0'):<Icon name="lock" size={12}/>}</button>)}<div className="path-end"><Icon name="trophy" size={18}/><span>{module.badge}</span></div></div></div></section>
 <div className="workbench"><section className="lesson-pane" aria-label={t('Ders anlatımı ve görevler')}><div className="zone-marker zone-marker-briefing"><span>01 · BRIEFING</span><b>{t('Oku · görevi anla')}</b></div><LessonTabs key={level.key} level={level} done={current.done}>
 <Prediction prediction={predictionFor(level,language)} choice={current.predictionChoice} onChoice={predictionChoice=>setCurrent(value=>({...value,predictionChoice}))}/><section className={`mission ${isComplete?'mission-done':''}`}><div className="mission-heading"><span><Icon name="flag" size={17}/>{t('Şimdi uygula.')}</span><b>{current.done}/{level.steps.length}</b></div><ProgressBar value={current.done} max={level.steps.length} label={t('Görev ilerlemesi')}/><ol className="task-list">{level.steps.map((step,i)=><li key={i} className={i<current.done?'task-done':i===current.done?'task-current':'task-future'}><span className="task-index">{i<current.done?<Icon name="check" size={13}/>:i+1}</span><div><p>{step.text}</p>{i===current.done&&<span className="task-status">{t('TERMİNALDE SIRA SENDE')}</span>}</div></li>)}</ol>{task?<div className="task-help"><button className="hint-button" onClick={()=>{setHint(h=>Math.min(2,h+1));setCurrent(value=>({...value,assisted:true}));}}><Icon name="hint" size={16}/>{t('İpucu')} {hint?`${hint}/2`:''}</button><button className="solution-button" onClick={()=>{setSolution(v=>!v);setCurrent(c=>({...c,assisted:true}));}}>{t('Çözümü')} {solution?t('gizle'):t('gör')}</button>{hint>0&&<div className="hint-bubble"><b>{hint===1?t('Bir yön işareti'):t('Sözdizimi desteği')}</b><p>{hint===1?task.hint:task.syntaxHint}</p></div>}{solution&&<ReferenceSolution step={task} onCommand={value=>{setCommand(value);inputRef.current?.focus();}}/>}<button className="goal-check" onClick={()=>{const assessment=evaluateTask(current.lab,task.goal,current.taskEvidence);const final=assessment.met&&current.done===level.steps.length-1?evaluateTask(current.lab,level.completionGoal,current.taskEvidence):{unmet:[]};setCurrent(value=>({...value,feedback:[...assessment.unmet,...final.unmet]}));if(assessment.met&&!final.unmet.length)notify(t('Hedef durumu hazır. Bu adımın doğrulama komutunu çalıştır.'));}}>{t('Hedefi kontrol et')}</button>{current.feedback?.length>0&&<ul className="goal-feedback" aria-live="polite">{current.feedback.map((item,index)=><li key={index}>{t(item.message,item.values)}</li>)}</ul>}</div>:<div className="mission-success"><Icon name="check" size={20}/><p><b>{t('İstenen durum doğrulandı.')}</b><span>{t('Bu laboratuvarı tamamladın.')}</span></p><button className="button primary" onClick={()=>id<128?go(id+1):setModal('badges')}>{id<128?t('Sonraki seviye'):t('Rozetlerini gör')}<Icon name="arrow" size={16}/></button></div>}</section>
 {isComplete&&level.debrief&&<section className="challenge-debrief"><h2>{t('Çözüm değerlendirmesi')}</h2><p>{level.debrief}</p></section>}
 </LessonTabs>{progress.practice[progressKey]&&<div className="practice-status"><span>{t('{0} başarılı çalışma',[progress.practice[progressKey].count])}</span><span>{progress.practice[progressKey].lastIndependentSuccess?t('Son yardımsız başarı: {0}',[progress.practice[progressKey].lastIndependentSuccess]):t('Henüz yardımsız tekrar yok')}</span></div>}<details className="personal-notes"><summary><Icon name="file" size={16}/>{t('Kendi notların')} <span>{progress.notes[progressKey]?.length?t('Kaydedildi'):t('Sadece bu tarayıcıda')}</span></summary><textarea aria-label={t('Bu seviye için notlarım')} placeholder={t('Aklımda kalan ayrım, yeni bir soru…')} maxLength={5000} value={progress.notes[progressKey]||''} onChange={e=>setProgress(p=>({...p,notes:{...p.notes,[progressKey]:e.target.value}}))}/></details><div className="lesson-pagination"><button disabled={id===1} onClick={()=>go(id-1)}><Icon name="arrow" size={15} style={{transform:'rotate(180deg)'}}/>{t('Önceki')}</button><button onClick={()=>openCourse(level.module)}>{t('8 seviyeye bak')}<Icon name="grid" size={14}/></button></div></section>
 <Workspace key={level.key} state={current.lab} level={level} sequence={sequence} entries={current.entries} onCommand={execute} command={command} setCommand={setCommand} inputRef={inputRef} history={current.history} drafts={current.drafts} onDrafts={drafts=>setCurrent(value=>({...value,drafts}))} selectedFile={current.selectedFile} onSelectedFile={selectedFile=>setCurrent(value=>({...value,selectedFile}))} previousState={current.previousState} activeTask={task?.text} onFiles={files=>setCurrent(c=>({...c,lab:{...c.lab,files}}))} notify={notify} settings={progress.settings} onSetting={setting}/></div></div></div></ExpeditionShell>
 <PracticeCenter open={modal==='practice'} onClose={()=>setModal('')} progress={progress} levels={levels} challengeKinds={challengeKinds} onReview={next=>go(next,{fresh:true})} onAllReviews={allReviews} onChallenge={startChallenge}/>
 <Modal open={modal==='course'} onOpenChange={v=>!v&&setModal('')} title={t('Öğrenme yolu')} description={t('16 modül, 128 laboratuvar. Kavramı oku, dene ve sonucu doğrula.')} wide><div className="course-controls"><div className="search-field"><Icon name="search"/><input id="course-search" aria-label={t('Seviye ara')} placeholder="Pod, Secret, autoscaling…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filter-row"><select aria-label={t('Modül filtresi')} value={courseModule??'all'} onChange={e=>setCourseModule(e.target.value==='all'?null:Number(e.target.value))}><option value="all">{t('Bütün modüller')}</option>{modules.map(m=><option key={m.id} value={m.id}>{m.id+1}. {m.title}</option>)}</select><select aria-label={t('İlerleme filtresi')} value={courseFilter} onChange={e=>setCourseFilter(e.target.value)}><option value="all">{t('Bütün seviyeler')}</option><option value="open">{t('Sıradaki açık seviyeler')}</option><option value="done">{t('Tamamlananlar')}</option><option value="bookmarked">{t('Yer işaretleri')}</option><option value="review">{t('Tekrar önerilenler')}</option><option value="assisted">{t('Yardımsız tekrar bekleyenler')}</option></select><span>{t('{0} seviye',[courseLevels.length])}</span></div></div><div className="course-list" tabIndex={0} role="region" aria-label={t('Filtrelenen seviyeler')}>{courseLevels.length?courseLevels.map(l=><button key={l.id} className={`course-row ${l.id===id?'current':''}`} disabled={!isUnlocked(progress,l.id)} onClick={()=>go(l.id,{fresh:['review','assisted'].includes(courseFilter)})}><span className="course-id">{padded(l.id)}</span><div><small>{modules[l.module].title}</small><strong>{l.title}</strong><p>{t('{0} görev · {1} dk · {2} XP',[l.steps.length,l.minutes,l.xp])}</p></div><Icon name={progress.completed[l.key]?'check':isUnlocked(progress,l.id)?'arrow':'lock'} size={17}/></button>):<p className="empty-message">{t('Bu filtreye uyan seviye yok.')}</p>}</div><p className="dialog-footnote">{t('Sırayla ilerlemek temelleri pekiştirir. Belirli bir konuyu incelemek için Ayarlar’dan serbest keşfi açabilirsin.')}</p></Modal>
 <Modal open={modal==='glossary'} onOpenChange={v=>!v&&setModal('')} title={t('Kavram sözlüğü')} description={t('{0} kavram. Ezberlenecek tanımlar değil, karıştırılmaması gereken ayrımlar.',[glossary.length])} wide><div className="search-field glossary-search"><Icon name="search"/><input aria-label={t('Sözlükte ara')} placeholder={t('Örn. readiness veya PVC')} value={glossarySearch} onChange={e=>setGlossarySearch(e.target.value)}/></div><div className="glossary-grid">{glossary.filter(g=>searchText(`${g.term} ${g.definition}`).includes(searchText(glossarySearch))).map(g=><article key={g.term}><span>{g.category}</span><h3>{g.term}</h3><p>{g.definition}</p></article>)}</div></Modal>
 <Modal open={modal==='reference'} onOpenChange={v=>!v&&setModal('')} title={t('Terminal cep rehberi')} description={t('NAME, IMAGE ve FILE yer tutucularını görevdeki değerlerle değiştir. lab komutları Kubernetes komutu değildir.')} wide><div className="cheat-grid">{cheats.map(([title,commands])=><section key={title}><h3>{title}</h3><pre>{commands}</pre></section>)}</div><p className="dialog-footnote">{t('Tırnaklar ve seçenek sırası desteklenir; pipe, shell, gerçek ağ ve dosya sistemi desteklenmez. Tam yerel liste için terminalde help yaz.')}</p></Modal>
 <Modal open={modal==='badges'} onOpenChange={v=>!v&&setModal('')} title={t('Sefer rozetleri')} description={t('{0} seviye tamamlandı · {1} XP · {2} günlük öğrenme serisi',[completedCount,formatNumber(xpTotal(progress)),streak(progress)])} wide><div className="badge-grid">{modules.map(m=><div key={m.id} className={`badge-card ${moduleDone(progress,m.id)?'earned':''}`}><span className="badge-seal"><Insignia module={m.id} size={60}/></span><span className="eyebrow">{t('MODÜL')} {m.id+1}</span><h3>{m.badge}</h3><p>{levels.filter(l=>l.module===m.id&&progress.completed[l.key]).length}{t('/8 seviye')}</p>{progress.quiz[m.id]&&<small>{t('✓ Kavram kontrolü')}</small>}</div>)}</div><p className="dialog-footnote">{t('Rozetler bu aracın öğrenme ilerlemesidir; bir sertifika veya gerçek küme yeterlilik belgesi değildir.')}</p></Modal>
 <Modal open={modal==='settings'} onOpenChange={v=>!v&&setModal('')} title={t('Seyir ayarları')} description={t('Öğrenme yolu sana uysun. İlerleme bu cihazın tarayıcısında saklanır.')}><div className="settings-body">{[['free',t('Serbest keşif'),t('Ön koşulları beklemeden bütün seviyeleri aç. XP yalnız görev tamamlandığında kazanılır.')],['reduced',t('Hareketi azalt'),t('Olayları anında göster; animasyonları azalt. Sistem tercihi de dikkate alınır.')],['sound',t('Tamamlama sesi'),t('Bir seviye tamamlandığında kısa bir ses çal. Varsayılan kapalıdır.')]].map(([key,title,desc])=><label className="setting-row" key={key}><span><b>{title}</b><small>{desc}</small></span><input type="checkbox" checked={progress.settings[key]} onChange={e=>setting(key,e.target.checked)}/></label>)}<div className="data-section"><h3>{t('İlerleme seninle gelsin.')}</h3><p>{t('Başka cihaza geçmeden JSON yedeği indir. Dosya notlarını, rozetlerini ve ayarlarını içerir; terminal oturumunu içermez.')}</p><div className="button-row"><button className="button secondary" onClick={()=>download('learn-k8s-progress.json',JSON.stringify(progress,null,2))}><Icon name="download"/>{t('Dışa aktar')}</button><button className="button secondary" onClick={()=>importRef.current?.click()}><Icon name="upload"/>{t('İçe aktar')}</button></div><input ref={importRef} type="file" accept="application/json,.json" hidden onChange={e=>importProgress(e.target.files?.[0])}/></div><button className="danger-link" onClick={()=>{if(window.confirm(t('Bütün ilerleme, not ve rozetler bu tarayıcıdan silinsin mi? Bu işlem geri alınamaz.'))){const p=freshProgress();setProgress(p);try{clearSession(localStorage);localStorage.removeItem(LEGACY_PROGRESS_KEY);}catch{}sessions.current={};setView('lab');setId(1);setCurrent(session(levels[0]));setCommand('');setModal('');closeReward();setHint(0);setSolution(false);history.replaceState(null,'','#level=1');notify(t('Yerel öğrenme kaydı sıfırlandı.'));}}}>{t('Bütün yerel ilerlemeyi sil')}</button></div></Modal>
 <Modal open={modal==='about'} onOpenChange={v=>!v&&setModal('')} title={t('Bu bir öğrenme modeli.')} description={t('Gerçek Kubernetes çalıştırmadan doğru zihinsel modeli kurmaya odaklanır.')}><div className="about-body"><h3>{t('Durum gerçekten değişir; altyapı çalışmaz.')}</h3><p>{t('Komutlar bellek içindeki kaynak nesnelerini değiştirir. Controller, scheduler, Service hedefleri, sınırlı RBAC ve ağ politikası kuralları sonucu hesaplar. Görevler bu sonuçlara bakar.')}</p><h3>{t('Neleri sadeleştiriyoruz?')}</h3><p>{t('Rollout anlık ve kapasite bakımından basitleştirilmiştir; maxSurge, backoff, probe süreleri, CPU throttling, gerçek disk verisi, CNI, TLS, sertifika ve Helm template motoru çalışmaz. lab tick gerçek zaman değildir.')}</p><h3>{t('Güvenlik ve gizlilik')}</h3><p>{t('Hesap, analiz takibi veya sunucu isteği yoktur. İlerleme localStorage’da tutulur. Gerçek Secret, parola, kubeconfig veya şirket manifestlerini buraya yapıştırma. Dış doküman bağlantıları ayrı sekmede açılır.')}</p><h3>{t('Gerçek kümeye geçiş')}</h3><p>{t('Burada öğrendiğin komutların gerçek ortamda kaynak oluşturabileceğini veya silebileceğini unutma. Ayrı bir kind/minikube çalışma kümesi, doğru context ve resmî dokümanlarla devam et.')}</p><a className="source-link" href="https://kubernetes.io/docs/tutorials/kubernetes-basics/" target="_blank" rel="noopener noreferrer">Kubernetes Basics<Icon name="external" size={14}/></a></div></Modal>
 <Modal open={resetDialog} onOpenChange={setResetDialog} title={t('Bu laboratuvar yeniden başlasın mı?')} description={t('Kaynaklar, terminal geçmişi ve bu oturumdaki YAML değişiklikleri başlangıca döner. Kazanılmış XP, notlar ve rozetler silinmez.')}><div className="confirm-actions"><button className="button secondary" onClick={()=>setResetDialog(false)}>{t('Vazgeç')}</button><button className="button primary" onClick={restart}><Icon name="reset"/>{t('Laboratuvarı sıfırla')}</button></div></Modal>
 {reward&&<PixelConfetti reduced={rewardReduced}/>}
 <Modal open={reward} onOpenChange={v=>!v&&closeReward()} className="reward-dialog" overlayClassName="reward-overlay" focusContent returnFocusRef={inputRef} title={id===128?t('Küme kaptanı, sefer tamamlandı.'):id%8===0&&moduleDone(progress,level.module)?t('{0} rozeti senin.',[module.badge]):t('Bir durak daha geride.')} description={id%8===0&&moduleDone(progress,level.module)?t('Bu modülün sekiz laboratuvarını da tamamladın.'):t('Komutu çalıştırdın. İstenen sonucu doğruladın.')}><div className="reward-body"><div className="reward-seal"><Insignia module={level.module} size={76}/></div><div className="reward-meta"><span>LAB {padded(id)} {t('TAMAMLANDI')}</span><strong>{rewardXp?`+${rewardXp} XP`:t('Tekrar tamamlandı')}</strong></div><p>{level.title}</p>{level.debrief&&<section className="challenge-debrief"><h3>{t('Çözüm değerlendirmesi')}</h3><p>{level.debrief}</p></section>}{current.assisted&&<span className="guided-completion">{t('Rehber desteğiyle öğrenmek de ilerlemektir.')}</span>}{id%8===0&&<div className="quiz-box"><span className="eyebrow">{t('KAVRAM KONTROLÜ · İSTEĞE BAĞLI')}</span><h3>{quizzes[level.module].question}</h3>{quizzes[level.module].options.map((option,i)=><button key={i} className={quizChoice===i?(i===quizzes[level.module].answer?'correct':'incorrect'):''} onClick={()=>{setQuizChoice(i);if(i===quizzes[level.module].answer)setProgress(p=>({...p,quiz:{...p.quiz,[level.module]:true}}));}}>{option}</button>)}{quizChoice!==null&&<p role="status">{quizChoice===quizzes[level.module].answer?t('Doğru. '):t('Bir daha düşün. ')}{quizzes[level.module].explanation}</p>}</div>}<button className="button primary reward-next" onClick={()=>{closeReward();if(id<128)go(id+1);else setModal('badges');}}>{id===128?t('Yolculuğunu gör'):t('Sonraki laboratuvara geç')}<Icon name="arrow"/></button><button className="text-button" onClick={closeReward}>{t('Burada denemeye devam et')}</button></div></Modal>
 {toast&&<div className="toast" role="status"><Icon name="info" size={17}/>{toast}<button aria-label={t('Bildirimi kapat')} onClick={()=>setToast('')}><Icon name="close" size={14}/></button></div>}
 </Tooltip.Provider>;
}
