// Import order is the pedagogical order; each module registers exactly eight labs.
import './curriculum/01.js';
import './curriculum/02.js';
import './curriculum/03.js';
import './curriculum/04.js';
import './curriculum/05.js';
import './curriculum/06.js';
import './curriculum/07.js';
import './curriculum/08.js';
import './curriculum/09.js';
import './curriculum/10.js';
import './curriculum/11.js';
import './curriculum/12.js';
import './curriculum/13.js';
import './curriculum/14.js';
import './curriculum/15.js';
import './curriculum/16.js';
import {levels} from './curriculum/core.js';
export {levels,modules,CURRICULUM_VERSION,E,R,N,C,ALL} from './curriculum/core.js';
export {LEGACY_ID_TO_KEY,KEY_TO_LEGACY_ID} from './curriculum/legacy.js';
export const levelsByKey = Object.freeze(Object.fromEntries(levels.map(level => [level.key, level])));
