export const glossary=[
 ['API server','Kubernetes API isteklerini karşılayan, doğrulayan ve küme durumuna erişimin giriş noktası olan bileşen.','architecture'],
 ['etcd','Küme durumunun tutarlı anahtar-değer deposu. Uygulamanın veritabanı veya Pod içindeki disk değildir.','architecture'],
 ['Scheduler','Node atanmamış Pod için request, kısıt ve uygunluk bilgilerine göre node seçer.','architecture'],
 ['Controller','Gözlenen durumu istenen duruma yaklaştırmak için tekrar tekrar çalışan kontrol döngüsü.','architecture'],
 ['Kubelet','Bir node üzerinde Pod ve container yaşam döngüsünü runtime ile koordine eden ajan.','architecture'],
 ['Container runtime','Container süreçlerini çalıştıran runtime katmanı. Kubernetes CRI aracılığıyla runtime ile konuşur.','architecture'],
 ['Image','Uygulama dosyaları ve başlatma bilgilerini paketleyen salt okunur şablon. Image bir çalışan süreç değildir.','container'],
 ['Tag ve digest','Tag insan tarafından kullanılan, değişebilen bir etikettir. Digest belirli image içeriğini adresleyen özet kimliğidir.','container'],
 ['Pod','Birlikte zamanlanan container grubu; aynı Pod container’ları ağ bağlamını ve tanımlanan volume’ları paylaşabilir.','workload'],
 ['Deployment','Genellikle stateless uygulamalar için Pod template, replica ve rollout yaşam döngüsünü yöneten kaynak.','workload'],
 ['ReplicaSet','Seçicisiyle eşleşen istenen sayıda Pod’u tutan controller. Deployment çoğunlukla bunu yönetir.','workload'],
 ['StatefulSet','Kararlı ordinal Pod kimlikleri ve depolama ilişkileri gereken iş yükleri için controller. Veritabanı replikasyonu kurmaz.','workload'],
 ['DaemonSet','Uygun node’larda birer Pod çalıştıran controller. Node ajanları yaygın kullanım alanıdır.','workload'],
 ['Job','Başarıyla tamamlanması beklenen sınırlı bir işi yöneten kaynak. Yeniden denemeler için iş idempotent tasarlanmalıdır.','workload'],
 ['CronJob','Zaman çizelgesine göre Job oluşturan kaynak. Tam olarak bir kez çalıştırma garantisi değildir.','workload'],
 ['Namespace','Aynı kümede kaynak isimlerini ve bazı politikaları kapsamlara ayırır. Tek başına tam güvenlik izolasyonu değildir.','organization'],
 ['Context','kubectl bağlantısında küme, kimlik ve varsayılan namespace bilgilerinin seçilen birleşimi.','organization'],
 ['Label / selector','Label nesne üzerindeki anahtar-değer etiketidir. Selector bu etiketlerle kaynakları seçer.','organization'],
 ['Annotation','Araçlar ve insanlar için seçici amaçlı olmayan ek metadata. Büyük veri depolamak için kullanılmamalı.','organization'],
 ['Desired / observed state','spec istenen yapılandırmayı, status sistemin gözlediği durumu ifade eder. Yakınsama her zaman anlık değildir.','architecture'],
 ['Service','Değişen Pod hedeflerinin önünde kararlı erişim soyutlaması. Selector ve hazır endpoint’ler arasındaki ilişki önemlidir.','network'],
 ['ClusterIP','Service’in küme içi sanal IP erişim türü. Normalde internetten doğrudan erişim sağlamaz.','network'],
 ['NodePort','Service’i node adreslerindeki ayrılmış bir port üzerinden erişilebilir kılan tür. Ağ ve güvenlik kuralları yine gereklidir.','network'],
 ['EndpointSlice','Service hedeflerinin adres, port ve hazır olma bilgilerinin parçalara ayrılmış temsilidir.','network'],
 ['Ingress','HTTP/HTTPS host ve path kurallarını Service’lere yönlendirme tanımı. Çalışan bir Ingress controller gerekir.','network'],
 ['Gateway API','Kubernetes servis ağındaki yönlendirme ve gateway sorumluluklarını daha ayrıntılı ayıran API ailesi. Bu sürümde yalnız referans olarak anlatılır.','network'],
 ['NetworkPolicy','Seçili Pod’ların izinli ağ bağlantılarını tanımlar. Destekleyen ağ eklentisi gerekir; RBAC yerine geçmez.','network'],
 ['ConfigMap','Gizli olmayan yapılandırma verisi. Environment olarak alınan değerler mevcut süreçte otomatik yenilenmez.','config'],
 ['Secret','Hassas veri için ayrı API nesnesi. Base64 bir şifreleme yöntemi değildir; erişim ve at-rest güvenliği ayrıca gerekir.','config'],
 ['Request','Scheduler’ın yerleşim için dikkate aldığı kaynak isteği. Gerçek anlık kullanım değeri değildir.','resources'],
 ['Limit','Runtime tarafından uygulanan kaynak sınırı. CPU ve bellekte aşım davranışları farklıdır.','resources'],
 ['Millicore','1000m = 1 CPU birimi. 250m dörtte bir CPU isteğini ifade eder; node’a özel sabit saat hızı değildir.','resources'],
 ['Taint / toleration','Taint node’daki itme kuralı, toleration bu kurala karşı izin tanımıdır. Toleration tek başına o node’a yerleşmeyi zorunlu kılmaz.','resources'],
 ['Readiness probe','Uygulamanın trafik almaya hazır olup olmadığını kontrol eder. Başarısızlık tek başına container restart sebebi değildir.','health'],
 ['Liveness probe','Container’ın yeniden başlatılmasının gerekip gerekmediğini kontrol eder. Yanlış probe tekrar başlatma döngüsü yaratabilir.','health'],
 ['Startup probe','Yavaş başlatılan uygulamanın başlangıcını kontrol eder; başarılı olana kadar diğer probe’ları koruyabilir.','health'],
 ['Init container','Normal uygulama container’larından önce tamamlanması gereken başlatma işi.','health'],
 ['PVC / PV','PersistentVolumeClaim depolama talebi, PersistentVolume kümedeki depolama kaynağıdır. Bağlanma ve reclaim politikaları ayrıdır.','storage'],
 ['StorageClass','Dinamik depolama sağlama politikasını ve provisioner seçimini tanımlar. Bir fiziksel disk nesnesi değildir.','storage'],
 ['emptyDir','Pod ömrüne bağlı geçici volume. Container restart’ında kalabilir; Pod silindiğinde veri ömrü sona erer.','storage'],
 ['ServiceAccount','Namespaced iş yükü kimliği. RoleBinding olmadan sadece kimlik varlığı yetki vermez.','security'],
 ['RBAC','Role kuralları hangi eylemlerin yapılabildiğini, RoleBinding ise hangi kimliklere atandığını tanımlar.','security'],
 ['SecurityContext','Container veya Pod için kullanıcı, ayrıcalık ve işletim sistemi güvenlik seçeneklerini tanımlar.','security'],
 ['HPA','Bir metrik hedefine göre workload replica sayısını ayarlar. Node eklemekten sorumlu değildir.','resilience'],
 ['PDB','Gönüllü kesintilerde izin verilen Pod kaybını sınırlar. Bütün node arızalarını önleyen bir garanti değildir.','resilience'],
 ['Cordon / drain','Cordon yeni yerleşimi kapatır. Drain mevcut uygun iş yüklerini güvenli tahliye etmeye çalışır.','resilience'],
 ['Helm chart / release','Chart parametreli kaynak paketidir; release o paketin kurulmuş, geçmişi takip edilen örneğidir.','tooling'],
 ['GitOps','Git’te tanımlı istenen durumu bir controller ile izleyip yakınsama yaklaşımı. Sadece Git’ten kubectl çalıştırmak değildir.','tooling'],
].map(([term,definition,category])=>({term,definition,category}));
export const quizzes=[
 ['Image ile container arasındaki fark hangisidir?',['Image paket; container o paketten başlatılan süreç örneğidir.','Image çalışan süreçtir.','İkisi aynı kaynak türüdür.'],0,'Bir image dururken hiç container çalışmıyor olabilir.'],
 ['Pod’u uygun node’a atayan bileşen hangisidir?',['etcd','Scheduler','Service'],1,'Scheduler yerleşim seçer; kubelet seçilen node üzerinde çalışmayı koordine eder.'],
 ['Bare Pod silinince neden geri gelmez?',['Her Pod kalıcıdır.','Namespace yanlışsa gelir.','Onu yeniden üretecek workload controller’ı yoktur.'],2,'Deployment tarafından yönetilen Pod farklı bir yaşam döngüsüne sahiptir.'],
 ['Aynı manifesti tekrar apply etmek neyi hedefler?',['Her seferinde yeni isimli kopya üretmeyi','Tanımlı istenen duruma yakınsamayı','Tüm namespace’i silmeyi'],1,'Aynı tür/namespace/ad nesnesi güncellenir; isimleri değiştirirsen yeni nesneler oluşur.'],
 ['Image değişikliği Deployment’ın hangi bölümündedir?',['Pod template','Service clusterIP','Node taint'],0,'Template değişikliği yeni rollout revision’ı tetikler.'],
 ['Service var ama endpoint yok. Önce neyi incelersin?',['Helm sürümünü','Terminal rengini','Selector etiketleri ve Pod readiness durumunu'],2,'Service nesnesinin varlığı sağlıklı backend garantisi değildir.'],
 ['Secret içindeki base64 veri şifrelenmiş midir?',['Evet, anahtarsız açılamaz.','Hayır; kodlama, şifreleme değildir.','Yalnız cluster içinde şifrelenmiştir.'],1,'At-rest şifreleme ve erişim kontrolü ayrıca yapılandırılır.'],
 ['Toleration tek başına neyi garanti etmez?',['O node’a yerleşmeyi','Taint’e tolerans tanımlamayı','Taint etkisiyle eşleştirilmeyi'],0,'Zorunlu yerleşim için uygun node selector veya affinity kuralları gerekir.'],
 ['Readiness başarısız, container Running. Ne beklenir?',['Her zaman restart','Pod otomatik silinir','Pod yeni Service trafiği için hazır hedef sayılmaz.'],2,'Liveness ile readiness farklı sorular sorar.'],
 ['StatefulSet otomatik olarak neyi kurmaz?',['Ordinal Pod isimlerini','Veritabanı replikasyonu ve yedeklemeyi','Kararlı kimlik düzenini'],1,'Uygulama düzeyindeki veri tutarlılığı ve yedekleme ayrı sorumluluktur.'],
 ['Role ile kimlik arasındaki atamayı hangi kaynak kurar?',['RoleBinding','ConfigMap','EndpointSlice'],0,'Role ne yapılabilir, binding kim yapabilir sorusunu yanıtlar.'],
 ['CronJob suspend=true, mevcut Job’u otomatik iptal eder mi?',['Evet','Hayır','Yalnız gece'],1,'Suspend yeni planlanan işlerin başlamasını kontrol eder.'],
 ['Configured çıktısı neyi tek başına kanıtlamaz?',['API yazısının kabulünü','Nesne adını','Uygulamanın hazır ve erişilebilir olduğunu'],2,'Rollout, readiness ve uçtan uca istekle ayrı doğrulama gerekir.'],
 ['CPU utilization HPA hedefinin paydası nedir?',['Node sayısı','CPU request','CPU limit'],1,'Bu yüzden request olmayan bir container kullanım yüzdesi hesaplamasını engelleyebilir.'],
 ['NetworkPolicy için ne gereklidir?',['Politikayı uygulayan ağ eklentisi','Mutlaka Helm','Her Pod’a public IP'],0,'API nesnesinin varlığı veri düzlemi uygulamasının yerine geçmez.'],
 ['Bir saha düzeltmesini nasıl bitirirsin?',['Komut başarılı yazdıysa bırakırım.','Kaynakları rastgele silerim.','İstenen durumu ve kullanıcıya ulaşan sonucu doğrularım.'],2,'Gözlem → hipotez → küçük düzeltme → doğrulama, tekrar kullanılabilir bir döngüdür.'],
].map(([question,options,answer,explanation],id)=>({id,question,options,answer,explanation}));
export const cheats=[
 ['Keşfet','kubectl get pods -A\nkubectl get pods -o wide\nkubectl describe pod NAME\nkubectl get events'],
 ['Oluştur','kubectl run NAME --image=nginx:1.27\nkubectl create deployment NAME --image=nginx:1.27\nkubectl apply -f FILE'],
 ['Yönet','kubectl scale deployment/NAME --replicas=3\nkubectl set image deployment/NAME CONTAINER=IMAGE\nkubectl rollout status deployment/NAME\nkubectl rollout undo deployment/NAME'],
 ['Bağlan','kubectl expose deployment NAME --port=80\nkubectl get endpointslices -o yaml\nkubectl exec client -- wget -qO- http://web:80\nkubectl port-forward service/web 8080:80'],
 ['İncele','kubectl logs NAME --previous\nkubectl top pods\nkubectl auth can-i list pods --as=system:serviceaccount:default:reader'],
 ['Lab yardımcıları','help\nls\ncat FILE\nlab tick\nlab load 90\nlab request web'],
];
